services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: bargenix
      POSTGRES_PASSWORD: backend_bargenix
      POSTGRES_DB: bargenix-product
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - '6379:6379'
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
